create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null,
  package text not null,
  created_at timestamptz not null default now()
);

alter table public.enquiries enable row level security;

drop policy if exists "Anyone can submit an enquiry" on public.enquiries;

create policy "Anyone can submit an enquiry"
on public.enquiries
for insert
to anon, authenticated
with check (
  char_length(trim(name)) > 0
  and char_length(trim(email)) > 0
  and char_length(trim(phone)) > 0
  and char_length(trim(package)) > 0
);
